version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./synapse_memory.json:/app/synapse_memory.json
      - ./llm_config.json:/app/llm_config.json
    environment:
      - FLASK_ENV=production
      - FLASK_APP=synapse_server_final.py
    restart: unless-stopped
    networks:
      - synapse-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - synapse-network

networks:
  synapse-network:
    driver: bridge