FROM node:18-alpine

WORKDIR /app

# Copiar archivos de configuraciu00f3n de dependencias
COPY synapse-ui-new/package.json synapse-ui-new/package-lock.json* ./

# Instalar dependencias
RUN npm install

# Copiar el cu00f3digo fuente
COPY synapse-ui-new/ ./

# Exponer el puerto que utiliza la aplicaciu00f3n
EXPOSE 3000

# Comando para iniciar la aplicaciu00f3n en modo desarrollo
CMD ["npm", "start"]