version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.refactored
    container_name: synapse-backend-refactored
    ports:
      - "5000:5000"
    volumes:
      - ./synapse_memory_migrated.json:/app/data/synapse_memory.json
      - ./synapse_config_migrated.json:/app/synapse_config.json
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - FLASK_APP=synapse_server_refactored.py
      - SYNAPSE_CONFIG=/app/synapse_config.json
    restart: unless-stopped
    networks:
      - synapse-network

  frontend:
    build:
      context: ./synapse-ui-new
      dockerfile: ../Dockerfile.frontend
    container_name: synapse-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - synapse-network

networks:
  synapse-network:
    driver: bridge